### ISSUE TITLE
High CPU usage after a while even with no workers running

### ISSUE THREAD

**Issue by Froghut** [HaveAGitGat/Tdarr#285]
**Describe the bug**
I have two Libraries with together ~ 15k files, 2 workers doing health scan, 1 worker doing conversion. After a while Tdarr responds slower and slower, so I stopped all workers, but the CPU usage was still at 100%. I checked using htop (sorry, linux noob, don't know what else to use). It seems quiate a few "ccextractor" processes keep getting "stuck", see the attached screenshot.

**To Reproduce**
Not sure, for me this will always happen after a while.

**Expected behavior**
I guess the processes should not keep getting "stuck".

**Screenshots**
https://i.imgur.com/bENtXet.png

**Desktop (please complete the following information):**
 - OS: Windows 10 running Tdarr in Docker.
 - Browser Firefox 81

**Comment by HaveAGitGat** [comment]
Hello, there is a significant performance update in the pro_nightly, just letting it run for a bit before updating things, there is also a slight change to the ccextractor process which should resolve that issue.

```
Performance Update
- Beta v1.3000 release [27th September 2020]:
- Massively increased performance across application (10* faster queue builder, 10* less DB usage, up to 200* faster file checking on startup, ~20% less RAM, far more responsive UI especially when scanning files)
- Fixed UI bug when creating a backup (backup size showing much lower than it should be)
- Fixed folder watch bug (error saying txt file doesn't exist)
- Moved scheduled hourly 'Scan (Find new)' to its own option instead of being enabled when 'Scan on start' enabled.
- Beta v1.3001 release [1st October 2020]:
- Massively reduced system load when running 'Scan (Find New)' or when folder watcher adding lots of files (~150* faster scanner prep time with 100,000 file library)
- Fixed DB initialisation memory bug on startup if 30,000+ files

```

**Comment by HaveAGitGat** [comment]
Please use the latest Docker tag (Tdarr v1.3003), which has the performance enhancements in. Re-open if needed.

**Comment by idittansikte** [comment]
@HaveAGitGat I am using v1.3003 and still see this issue. Tdarr is taking a whole CPU core for itself while idling. Is there perhaps a busy loop somewhere? FYI, I am not using pro version (yet, I'm still trialing it).
