### ISSUE TITLE
Plugin error! Error: Cannot find module '../methods/library.js'

### ISSUE THREAD

**Issue by cliny** [HaveAGitGat/Tdarr#336]
I'm trying to transcode to hevc, but it skips h264 files saying not required.

When I click the 'i' button, I see 
```
Plugin error! Error: Cannot find module '../methods/library.js'

Require stack:

- /app/Tdarr_Node/assets/app/plugins/Local/noop.js
```
My docker compose currently is
```
    tdarr:
        container_name: tdarr
        restart: unless-stopped
        volumes:
            - '/home/cliny/docker/tdarr/app/server:/app/server'
            - '/mnt/usbhdd:/usbhdd'
            - '/home/cliny/docker/tdarr/transcode_cache:/temp'
            - '/home/cliny/docker/tdarr/tdarr_configs:/app/configs'
        environment:
            - serverIP=tdarr
            - serverPort=8266
            - webUIPort=8265
            - TZ=Australia/Melbourne
            - PUID=1000
            - PGID=1000
        ports:
            - 8265:8265
            - 8266:8266
        image: 'haveagitgat/tdarr:2.00.02'
    tdarr_node:
        container_name: tdarr_node
        depends_on:
            - tdarr
        restart: unless-stopped
        volumes:
            - '/mnt/usbhdd:/usbhdd'
            - '/home/cliny/docker/tdarr/transcode_cache:/temp'
            - '/home/cliny/docker/tdarr/tdarr_configs:/app/configs'
        environment:
            - nodeID=cliny_tdarr_node_id
            - nodeIP=tdarr_node
            - nodePort=8267
            - serverIP=tdarr
            - serverPort=8266
            - TZ=Australia/Melbourne
            - PUID=1000
            - PGID=1000
        devices:
            - '/dev/dri:/dev/dri'
        image: 'haveagitgat/tdarr_node:2.00.02'
```
This only happens with plugins I create.
```

  module.exports.dependencies = [
    'import-fresh',
  ]

  module.exports.details = function details() {
        return {
          id: "IKrf4Pyln",
          Name: "convert to hevc",
          Type: "Video",
          Operation: "Transcode",
          Description: "convert to hevc",
          Version: "",
          Link: ""
        }
      }

  module.exports.plugin = function plugin(file) {

    const importFresh = require('import-fresh');
    const library = importFresh('../methods/library.js');

        //Must return this object at some point
        var response = {
           processFile : false,
           preset : '',
           container : '.mkv',
           handbrakeMode : false,
           ffmpegMode : true,
           reQueueAfter : true,
           infoLog : '',
      
        }

        response.infoLog += "" + library.filters.filterByCodec(file,"exclude","hevc").note
      
        if((true &&library.filters.filterByCodec(file,"exclude","hevc").outcome === true) || file.forceProcessing === true){
            response.preset = ' -Z "Very Fast 1080p30" -e qsv_h265 '
            response.container = '.mkv'
            response.handbrakeMode = true
            response.ffmpegMode = false
            response.reQueueAfter = true;
            response.processFile = true
            response.infoLog +=  "File is being transcoded using HandBrake \n"
            return response
           }else{
            response.processFile = false;
            response.infoLog += "File is being transcoded using HandBrake \n"
            return response
           }
      }
```
Currently version 2.00.02.
Thanks

**Comment by HaveAGitGat** [comment]
Hi thanks for this, if you update 2.00.02 it should now work.

**Comment by cliny** [comment]
> Hi thanks for this, if you update 2.00.02 it should now work.

I deleted my tdarr config folder and reinstalled. But I'm still getting the same error in 2.00.02

**Comment by tyhawk** [comment]
I had the same issue, but it seems to be fixed in version 2.00.02. I'm still testing though, but so far so good.

Unfortunately, I can only run 2.00.02 in docker. The Tdarr_Updater is still at version 2.00.01 (https://storage.googleapis.com/tdarr/versions/2.00.01/linux_x64/Tdarr_Updater.zip) and it doesn't download version 2.00.02. Hopefully the new version will be available for that platform too soon, so I can use my laptop as a second node.

**Comment by jasonsansone** [comment]
You can test 2.00.02 on Linux.  Change "latest" to "2.00.02" in the updater json config.

**Comment by tyhawk** [comment]
Just upgraded my amd64 linux node and both my docker nodes to 2.00.03. So far, my amd64 linux node seems to run fine, but on the docker nodes:
```
File has no title metadata fgn2k5HRo - Pre-processing
☒Plugin error! Error: Cannot find module '../methods/library.js' Require stack: - /app/Tdarr_Node/assets/app/plugins/Local/noop.js
```

**Comment by tyhawk** [comment]
I did some more testing and it seems this alert keeps coming up. It contains an error of a previous step, following by the alert from my local plugin, which is a Handbrake transcode with custom settings.
```
☒Audio stream detected as being unwanted, removing. Audio stream 0:a:0 ☒Cancelling plugin otherwise all audio tracks would be removed. NbRtsV1w6 - Pre-processing ☒Plugin error! Error: Cannot find module '../methods/library.js' Require stack: - /app/Tdarr_Node/assets/app/plugins/Local/noop.js
```
NbRtsV1w6.js is my local plugin:
```

  module.exports.dependencies = [
    'import-fresh',
  ]

  module.exports.details = function details() {
        return {
          id: "NbRtsV1w6",
          Name: "Tyhawk_Transcode_Series_720p_Resolution",
          Type: "Video",
          Operation: "Transcode",
          Description: "Transcodes files over 720p with my default 720p settings for TV shows. It will downmix audio to AAC stereo.",
          Version: "",
          Link: ""
        }
      }

  module.exports.plugin = function plugin(file) {

    const importFresh = require('import-fresh');
    const library = importFresh('../methods/library.js');

        //Must return this object at some point
        var response = {
           processFile : false,
           preset : '',
           container : '.mkv',
           handbrakeMode : false,
           ffmpegMode : true,
           reQueueAfter : true,
           infoLog : '',
      
        }

        response.infoLog += "" + library.filters.filterByResolution(file,"include","1080p,4KUHD,DCI4K,8KUHD").note
      
        if((true &&library.filters.filterByResolution(file,"include","1080p,4KUHD,DCI4K,8KUHD").outcome === true) || file.forceProcessing === true){
            response.preset = '--markers --optimize --align-av --encoder "x264" --encoder-preset slow --encoder-tune "film" --vb "1600" --no-turbo --vfr --audio 1 --aname "Stereo" --aencoder aac --ab 192 --mixdown stereo --normalize-mix 1 --crop "0:0:0:0" --maxWidth "1280" --maxHeight "720" --auto-anamorphic --comb-detect --deinterlace --decomb'
            response.container = '.mp4'
            response.handbrakeMode = true
            response.ffmpegMode = false
            response.reQueueAfter = true;
            response.processFile = true
            response.infoLog +=  "File is being transcoded using custom arguments \n"
            return response
           }else{
            response.processFile = false;
            response.infoLog += "File is being transcoded using custom arguments \n"
            return response
           }
      }

    ^J
```
I tested with 2 nodes: 1 docker node and an amd64 node running on my laptop, both running 2.00.03 (the one on my laptop states it is version 2.00.31). The library.js file is present on the tdarr_server:
```
Tdarr> ls -lah Plugins/methods/
total 12K
drwxr-xr-x 1 overlord overlord  74 Feb  5 08:49 ./
drwxr-xr-x 1 overlord overlord 100 Feb  5 08:49 ../
-rw-r--r-- 1 overlord overlord 773 Feb  5 08:49 actions.js
-rw-r--r-- 1 overlord overlord 719 Feb  5 08:49 filters.js
drwxr-xr-x 1 overlord overlord  28 Feb  1 13:00 library/
-rw-r--r-- 1 overlord overlord 399 Feb  5 08:49 library.js
```
It's also present on the amd64 tdarr_node:
```
> ls -lah /opt/tdarr/Tdarr_Node/assets/app/plugins/methods/
total 12K
drwxr-xr-x 1 overlord overlord  74  5 feb 09:31 ./
drwxr-xr-x 1 overlord overlord 100  5 feb 09:31 ../
-rw-r--r-- 1 overlord overlord 773  5 feb 09:31 actions.js
-rw-r--r-- 1 overlord overlord 719  5 feb 09:31 filters.js
drwxr-xr-x 1 overlord overlord  28  1 feb 08:55 library/
-rw-r--r-- 1 overlord overlord 399  5 feb 09:31 library.js
```
It doesn't seem to be present on the docker tdarr_node though:
```
oot@568ced0b9e31:/app/Tdarr_Node# ls -lah assets/app/plugins/
total 4.0K
drwxr-xr-x 1 Tdarr Tdarr   86 Feb  5 09:08 .
drwxr-xr-x 1 Tdarr Tdarr   48 Feb  5 08:48 ..
drwxr-xr-x 1 Tdarr Tdarr  332 Feb  5 09:08 Community
drwxr-xr-x 1 Tdarr Tdarr   24 Feb  5 09:08 Local
drwxr-xr-x 1 Tdarr Tdarr   92 Feb  5 08:49 node_modules
-rw-r--r-- 1 Tdarr Tdarr 1.3K Feb  5 08:49 package-lock.json
```
Can't find it in the Tdarr directory on the docker tdarr_node:
```
root@568ced0b9e31:/app# find . -name '*.js' -type f
./Tdarr_Node/assets/app/plugins/Community/Tdarr_Plugin_lmg1_Reorder_Streams.js
./Tdarr_Node/assets/app/plugins/Community/Tdarr_Plugin_MC93_Migz4CleanSubs.js
./Tdarr_Node/assets/app/plugins/Community/Tdarr_Plugin_078d_Output_embedded_subs_to_SRT_and_remove.js
./Tdarr_Node/assets/app/plugins/Community/Tdarr_Plugin_MC93_Migz3CleanAudio.js
./Tdarr_Node/assets/app/plugins/node_modules/callsites/index.js
./Tdarr_Node/assets/app/plugins/node_modules/parent-module/index.js
./Tdarr_Node/assets/app/plugins/node_modules/resolve-from/index.js
./Tdarr_Node/assets/app/plugins/node_modules/import-fresh/index.js
./Tdarr_Node/assets/app/plugins/Local/NbRtsV1w6.js
./Tdarr_Node/node_modules/@ffmpeg-installer/ffmpeg/index.js
./Tdarr_Node/node_modules/@ffmpeg-installer/ffmpeg/lib/verify-file.js
```
This is the section of my docker-compose file for the Tdarr_node:
```
  tdarr-node01:
    image: haveagitgat/tdarr_node:2.00.03
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
      - nodeID=pegasus
      - nodeIP=192.168.18.21
      - nodePort=8267
      - serverIP=192.168.18.20
      - serverPort=8266
    volumes:
      - downloads:/mnt/downloads
      - tvseries:/mnt/tvseries
      - speelfilms:/mnt/speelfilms
    networks:
      - traefik-public
    ports:
      - target: 8267
        published: 8267
        protocol: tcp
        mode: host
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      placement:
        constraints:
          - node.labels.traefik-public.tdarr_node1 == true
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    depends_on:
      - tdarr-server
```
I don't use a mounted volume for the node for the config as I don't need mappings and my config is fairly simple. The cache directory is also on a shared volume (/mnt/downloads/cache in my case) that all nodes and the server use (and is mounted exactly the same).

**So I think the issue is that the `app/plugins/methods/` directory is missing in the Tdarr_Node docker image, so the error is correct.**

@HaveAGitGat hope you can fix this issue soon, as it makes it impossible to run local plugins on the docker node.

**Comment by HaveAGitGat** [comment]
Seems something is preventing the `methods` folder being downloaded to the Node on your system.  Make sure the server is up and running before the node starts as that might be causing the issue.

The quick fix is to download it manually from Tdarr_Plugins:
https://github.com/HaveAGitGat/Tdarr_Plugins/tree/master/methods

Then put it next to the 'Local' plugins folder inside Tdarr_Node. On Docker this would be in `app/Tdarr_Node/assets/app/plugins`

![image](https://user-images.githubusercontent.com/43864057/107147372-f9d7cd80-694d-11eb-85e2-235a64d97c82.png)

**Comment by tyhawk** [comment]
I'm running in swarm mode with Portainer and all of the containers in one stack. The depend_on actually doesn't work in docker compose 3 in swarm mode, so the nodes have completed their startup before the server is running. I will seperate the stack into server and nodes so I can make sure the nodes start after the server is running.

I will test this tomorrow and get back to you.

**Comment by tyhawk** [comment]
I managed to find time to work on this now, and the docker node is transcoding with my local plugin, so it seems the issue was indeed that the server hadn't started up before the node did. It would be nice to have a failsafe for this behavour in the code at some point, though. ;-)

**Comment by HaveAGitGat** [comment]
I have added a failsafe to 2.00.04 so it will use the default community plugins repo to download that folder if the server is not running.
