### ISSUE TITLE
Age filter does not work correctly

### ISSUE THREAD

**Issue by CommandStorm5** [HaveAGitGat/Tdarr#387]
**Describe the bug**
A custom plugin with an Age filter that is supposed to include files older than X time does not transcode files that meet those requirements

**To Reproduce**
* Create a custom plugin
* Apply Age filter which includes files older than X time
* Add that plugin to a library
* Queue a file that should be transcoded due to age
* Said file gets skipped

**Expected behavior**
The file should get transcoded

**Screenshots**
![image](https://user-images.githubusercontent.com/52597821/109071559-2c2a4e80-76f4-11eb-89ab-28bae1a68cba.png)
![image](https://user-images.githubusercontent.com/52597821/109071584-32202f80-76f4-11eb-9104-57f0489fc8bb.png)

**Please provide the following information:**
- Config files 
- Tdarr_Server_Config.json 
```
{
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```
- Tdarr_WebUI_Config.json
```
{
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "serverPort": "8266"
}
```

- Log files 
- Tdarr_Server_Log.txt
```
[2021-02-24T22:51:41.503] [WARN] Tdarr_Server - Running inside a Docker container
[2021-02-24T22:51:42.204] [INFO] Tdarr_Server - ffprobePath:/app/Tdarr_Server/node_modules/ffprobe-static/bin/linux/x64/ffprobe
[2021-02-24T22:51:42.215] [INFO] Tdarr_Server - exiftoolPath:/app/Tdarr_Server/node_modules/exiftool-vendored.pl/bin/exiftool
[2021-02-24T22:51:42.227] [INFO] Tdarr_Server - CCExtractorPath:/app/Tdarr_Server/assets/app/ccextractor/ccextractor
[2021-02-24T22:51:42.530] [INFO] Tdarr_Server - Tdarr started.
[2021-02-24T22:51:42.531] [INFO] Tdarr_Server - Tdarr documents folder:/app/server
[2021-02-24T22:51:42.531] [INFO] Tdarr_Server - Checking directories
[2021-02-24T22:51:42.534] [INFO] Tdarr_Server - Tdarr_Server listening at http://localhost:8266
[2021-02-24T22:51:43.170] [INFO] Tdarr_Server - ---------------Binary tests start----------------
[2021-02-24T22:51:43.214] [INFO] Tdarr_Server - handbrakePath:HandBrakeCLI
[2021-02-24T22:51:43.284] [INFO] Tdarr_Server - ffmpegPath:ffmpeg
[2021-02-24T22:51:43.331] [INFO] Tdarr_Server - mkvpropedit:mkvpropedit
[2021-02-24T22:51:43.332] [INFO] Tdarr_Server - Binary test 1: handbrakePath working
[2021-02-24T22:51:43.332] [INFO] Tdarr_Server - Binary test 2: ffmpegPath working
[2021-02-24T22:51:43.333] [INFO] Tdarr_Server - Binary test 3: mkvpropeditPath working
[2021-02-24T22:51:43.333] [INFO] Tdarr_Server - ---------------Binary tests end-------------------
[2021-02-24T22:51:43.533] [WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI.
[2021-02-24T22:51:49.443] [INFO] Tdarr_Server - ---------------Scanner tests start----------------
[2021-02-24T22:51:49.444] [INFO] Tdarr_Server - Scanner test 1: FFprobe working
[2021-02-24T22:51:49.444] [INFO] Tdarr_Server - Scanner test 2: Exiftool working
[2021-02-24T22:51:49.445] [INFO] Tdarr_Server - Scanner test 3: Mediainfo working
[2021-02-24T22:51:49.446] [INFO] Tdarr_Server - Scanner test 4: CCExtractor working
[2021-02-24T22:51:49.446] [INFO] Tdarr_Server - ---------------Scanner tests end----------------
[2021-02-24T22:51:53.535] [INFO] Tdarr_Server - Database has finished initialising
[2021-02-24T22:51:53.536] [INFO] Tdarr_Server - Updating plugins
[2021-02-24T22:51:53.843] [INFO] Tdarr_Server - Cloning plugins
[2021-02-24T22:51:53.865] [INFO] Tdarr_Server - Turning folder watch on for:/media/anime
[2021-02-24T22:51:53.869] [INFO] Tdarr_Server - Turning folder watch on for:/media/shows
[2021-02-24T22:51:53.877] [INFO] Tdarr_Server - Turning folder watch on for:/media/movies
[2021-02-24T22:51:53.880] [INFO] Tdarr_Server - 30
[2021-02-24T22:51:53.925] [INFO] Tdarr_Server - Watcher SQU7vfkiJ launched
[2021-02-24T22:51:53.925] [INFO] Tdarr_Server - 30
[2021-02-24T22:51:53.965] [INFO] Tdarr_Server - Watcher sVsvkCA4l launched
[2021-02-24T22:51:53.965] [INFO] Tdarr_Server - 30
[2021-02-24T22:51:54.028] [INFO] Tdarr_Server - Watcher YdpxaHV-n launched
[2021-02-24T22:51:54.747] [INFO] Tdarr_Server - Finished downloading plugins!
[2021-02-24T22:51:55.361] [INFO] Tdarr_Server - SQU7vfkiJ: Creating folder watch for library:/media/anime
[2021-02-24T22:51:55.984] [INFO] Tdarr_Server - sVsvkCA4l: Creating folder watch for library:/media/shows
[2021-02-24T22:51:56.217] [INFO] Tdarr_Server - YdpxaHV-n: Creating folder watch for library:/media/movies
[2021-02-24T22:51:59.572] [INFO] Tdarr_Server - sVsvkCA4l: Initial scan complete. Ready for changes
[2021-02-24T22:51:59.919] [INFO] Tdarr_Server - SQU7vfkiJ: Initial scan complete. Ready for changes
[2021-02-24T22:52:00.027] [INFO] Tdarr_Server - YdpxaHV-n: Initial scan complete. Ready for changes
[2021-02-24T22:52:03.894] [INFO] Tdarr_Server - [10.357s]Plugin update finished
[2021-02-24T22:52:25.974] [INFO] Tdarr_Server - k-on
```
- Tdarr_WebUI_Log.txt
```
[2021-02-24T22:51:40.832] [ERROR] Tdarr_WebUI - Tdarr_Server is not alive at 0.0.0.0:8266 retrying
[2021-02-24T22:51:41.839] [ERROR] Tdarr_WebUI - Tdarr_Server is not alive at 0.0.0.0:8266 retrying
[2021-02-24T22:51:43.132] [INFO] Tdarr_WebUI - Tdarr_Server is alive at 0.0.0.0:8266
```

-Worker error: See screenshot above

 - OS: Linux
 - Browser Chrome
 - Version 2.00.06

**Additional context**
I was attempting to create a plugin that would downscale old files to 720p to save on disk space. My plugin above also had the resolution filter enabled, but I also tested the problem with only the age filter and nothing changed. Here is the file data:
```
  "file_size": 1217.9627437591553,
  "video_resolution": "1080p",
  "fileMedium": "video",
  "video_codec_name": "h264",
  "lastPluginDetails": "none",
  "processingStatus": false,
  "createdAt": 1614204271518,
  "bit_rate": 0,
  "statSync": {
    "mtimeMs": 1592507324611.927,
    "ctimeMs": 1610493423315.9307,
    "atime": "2021-01-28T04:03:42.073Z",
    "mtime": "2020-06-18T19:08:44.612Z",
    "ctime": "2021-01-12T23:17:03.316Z"
  }
```

**Comment by HaveAGitGat** [comment]
Hi, this should be fixed now. Restart the server and node and they will download the updated plugin library. Thanks.

**Comment by CommandStorm5** [comment]
Sadly, it still does not seem to be working correctly for me. Here is what happens:
An Exclude older than X hours filter excludes all files unconditionally
An Include older than X hours filter includes all files unconditionally
I have restarted both Tdarr and Tdarr_node multiple times, updated both Docker images, and recreated the plugins.
