### ISSUE TITLE
QSV GPU Health Checks are not working

### ISSUE THREAD

**Issue by Enigma0** [HaveAGitGat/Tdarr#546]
**Describe the bug**
Trying to do QSV GPU health checks (thorough) and they fail without starting.

**To Reproduce**
Set worker to 'qsv' and allow GPU tasks. Enable 1 GPU health checker.

**Expected behavior**
QSV GPU used for health checks.

**Screenshots**

**Please provide the following information:**

Command being executed is this which as you can see is not even close:

`-stats -v error -hwaccel nvdec -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 , -f null -max_muxing_queue_size 9999`

 - OS: Win 10 (Node) - Unraid for server
 - Browser Firefox
 - Version 2.00.13

**Comment by HaveAGitGat** [comment]
Should be fixed for .14. Using `-stats -v error -hwaccel qsv , -f null -max_muxing_queue_size 9999`

**Comment by Enigma0** [comment]
@HaveAGitGat Nice!

Unsure if this is a feature or bug but same deal with AMD GPU's, there's no option to select AMF/VCE/VCN (all the same I think) and they just fail as well.

**Comment by Enigma0** [comment]
@HaveAGitGat I think qsv health checks are still not working although the parameter is correct:

`-stats -v error -hwaccel qsv , -f null -max_muxing_queue_size 9999`

However the Intel GPU has no usage and the CPU does. It may have an auto-fallback to CPU or something like that.

**Comment by gogito** [comment]
> @HaveAGitGat I think qsv health checks are still not working although the parameter is correct:
> 
> `-stats -v error -hwaccel qsv , -f null -max_muxing_queue_size 9999`
> 
> However the Intel GPU has no usage and the CPU does. It may have an auto-fallback to CPU or something like that.

Have you solved it? 

I can use QSV transcode fine, although CPU usage is super high, like it's using 10 of the 12 threads on my 12400. intel_gpu_top does show the GPU being used though.

But when doing healthcheck, intel_gpu_top shows 0 gpu activity.

The iGPU was passed through to the container using gvt-G.

Also performance doesn't seem as high as it should. I get around 45fps doing 1080p h264 to 1080p h265 using Boosh QSV plugins.

When using VAAPI, the fps was similar but out of 2000+ files, around 50 or so always fail transcode and 23 or so always fail healthcheck so I tried QSV which always pass.
